### ISSUE TITLE
LaTeX source code

### ISSUE THREAD

**Issue by pkill37** [RJ-Jesus/Hybrid-Cryptography#1]
Hi,

Could you please share the LaTeX source code for the report? :)

I would put it under version control instead of the binary PDF file.

Thanks.

**Comment by rj-jesus** [comment]
Hi,

The source was intended to be public, but since I made this repository public shortly after handing the report in I decided it was best to keep it off of GitHub for the time being. Anyway, it is now in the LaTeX directory alongside the final PDF version.

Cumps,
Ricardo Jesus

**Comment by pkill37** [comment]
Thank you. :smile:
